#+TITLE: Sujet_genetique_depuis_elsevier
* KILL Chap 1
rien
* Chap 2
QCM 5

Le syndrome de Turner :

A. Correspond à la nullosomie de gènes portés par le chromosome Y

B. Peut se manifester à la naissance par un syndrome de Bonnevie-Ullrich

C. Se caractérise par une déficience intellectuelle

D. Se caractérise par une taille supérieure à la moyenne

E. Peut être dû à des anomalies de structure du chromosome X

QCM 6

Le syndrome de Klinefelter est caractérisé par :

A. Une déficience intellectuelle constante

B. La fréquence des mosaïques

C. Une infertilité

D. L'existence d'un chromosome X surnuméraire

E. Des malformations viscérales fréquentes

Syndrome de Turner

La formule chromosomique classique de ce syndrome est la formule 45,X qui fait qu'il est le plus souvent assimilé à la monosomie X. Cependant, il s'agit tout autant, si ce n'est plus, d'une nullosomie Y car le chromosome Y porte une douzaine de gènes à expression dosage-dépendante qui sont essentiels à la survie des embryons XY et qui possèdent un homologue échappant à l'inactivation sur le chromosome X [5]. La conséquence directe est que la très grande majorité (> 99 %) des embryons présentant un caryotype 45,X homogène ne se développent pas et qu'on peut se demander si ceux qui arrivent à terme et donnent des enfants atteints ne sont pas des mosaïques non détectées.

Décrit cliniquement par Henry H. Turner en 1938 [27], le syndrome qui porte son nom restera inexpliqué jusqu'en 1959 quand sera découverte l'anomalie chromosomique qui le caractérise [28]. Affectant environ 1/2 500 nouveau-né de sexe féminin, il peut se présenter à la naissance sous l'aspect d'un syndrome de Bonnevie-Ullrich associant une petite taille, un lymphœdème des mains et des pieds et un excès de peau au niveau de la nuque (pterygium colli). Des malformations cardiaques (coarctation de l'aorte) ou rénales (rein en fer à cheval) peuvent être présentes et repérables à l'échographie anténatale, de même que les anomalies au niveau de la nuque (hygroma kystique). Dans l'enfance, ce sont les problèmes de petite taille qui doivent être repérés et pris en charge et, à l'adolescence, une aménorrhée primaire traduira l'existence d'une dysgénésie gonadique pure (streak gonads) [29]. Il n'y a pas de déficience intellectuelle dans le syndrome de Turner et seules ont pu être décrites des particularités psychologiques particulières. Chez la femme adulte, des grossesses sont néanmoins possibles après don d'ovocytes mais doivent faire l'objet d'une surveillance cardio-vasculaire très rapprochée [30].

Au point de vue chromosomique, outre la formule chromosomique classique 45,X, le syndrome de Turner se caractérise par la fréquence des mosaïques dont la plus courante est de type 45,X/46,XX. Les mosaïques 45,X/46,XY existent également, avec un faible contingent de cellules Y positives, ce qui explique le développement phénotypique féminin. Elles doivent être recherchées systématiquement, par FISH ou par PCR, devant une formule 45,X apparemment homogène dans le sang car elles sont un facteur de mauvais pronostic pour le risque de transformation maligne des gonades dysgénésiques. Elles imposent donc une proposition de gonadectomie. À côté des anomalies de nombre, le syndrome de Turner peut être dû à l'existence d'une anomalie de structure d'un des chromosomes X comme un isochromosome X pour le bras long [46,X,i(Xq)] ou encore un anneau de l'X [46,X,r(X)] si la taille de ce dernier lui a fait perdre suffisamment de gènes. Il existe en effet des femmes porteuses d'un très grand anneau de l'X qui sont phénotypiquement normales et même fertiles. Une mention particulière doit être apportée concernant les anneaux de très petite taille qui ont perdu le locus Xist et ne peuvent donc plus s'inactiver. Ce sont eux qui donnent les rares cas de syndrome de Turner avec déficience intellectuelle et ils peuvent poser de difficiles interprétations en prénatal.
Syndrome de Klinefelter

Le syndrome de Klinefelter fut décrit cliniquement en 1942 par Harry F. Klinefelter à partir de neuf sujets présentant une gynécomastie bilatérale, des petits testicules, une aspermatogenèse avec fonction leydigienne normale ou peu diminuée et une FSH (pour follicle-stimulating hormone, hormone folliculo-stimulante) augmentée [31]. La formule chromosomique 47,XXY qui le caractérise sera la deuxième anomalie chromosomique humaine publiée, quelques jours après la trisomie 21 [32].

La prévalence du syndrome de Klinefelter dans la population générale est difficile à déterminer avec précision puisqu'environ deux tiers des sujets atteints ne sont jamais diagnostiqués [33]. Des études déjà anciennes réalisées sur des nombres importants de nouveau-nés non sélectionnés donnent une prévalence du syndrome comprise entre 1/700 et 1/1 000 garçons à la naissance [34–36].

Le diagnostic de syndrome de Klinefelter n'est pratiquement jamais porté à la naissance, sauf en cas de diagnostic prénatal fortuit fait pour une tout autre raison. Il faut donc attendre la puberté et l'âge adulte pour trouver des signes cliniques susceptibles d'aboutir à la réalisation d'un caryotype mais la variabilité interindividuelle de ces signes fait que le diagnostic peut être porté plus ou moins tôt. Ce qui caractérise les sujets Klinefelter de façon quasi constante est l'atteinte testiculaire, avec ou sans signe d'hypogonadisme, et surtout le petit volume testiculaire [33]. La cause principale de découverte de ce syndrome reste donc l'infertilité due à une azoospermie et cette anomalie chromosomique est diagnostiquée chez environ 3 % des hommes infertiles non sélectionnés mais chez plus de 10 % de ceux qui présentent une azoospermie sécrétoire [37].

Le syndrome de Klinefelter se caractérise par la fréquence des mosaïques qui, dans ce dernier cas, peuvent atteindre 20 % avec, comme anomalie la plus souvent rencontrée, une formule chromosomique de type 47,XXY/46,XY [38]. L'atteinte testiculaire dépend alors du pourcentage de cellules XXY et de leur localisation, notamment au niveau des gonades. Le diagnostic de ces mosaïques est d'une particulière importance car il conditionne en partie les chances de succès des biopsies testiculaires qui peuvent être proposées aux hommes Klinefelter. Il est maintenant en effet acquis que ces hommes, lorsqu'ils arrivent à produire quelques spermatozoïdes, le font à partir de cellules-souches normales XY et que, même s'ils sont XXY de façon homogène dans le sang, ce sont en fait des mosaïques au moins au niveau testiculaire [39].
* KILL Chap 3
* Chap 4
QCM 1

Concernant la transmission autosomique, quelles affirmations sont vraies ?

A. La transmission est de type horizontal

B. Le risque de récurrence est de 50 % si un des parents est atteint

C. Seuls les garçons sont malades

D. Un patient muté peut ne présenter aucun signe clinique

E. Un patient atteint aura forcément tous ses enfants atteints



* Chap 5

Les couples A-B et C-D vous consultent pour un conseil génétique. La sœur de Mme B et de Mr C était atteinte d'une maladie de Hurler. Il s'agit d'une maladie récessive autosomique qui atteint un enfant sur 90 000 naissances (1/90 000)

QCM 1

Concernant le risque de Mme B d'être hétérozygote pour la maladie de Hurler, quelle(s) proposition(s) est (sont) exacte(s) ?

A. Le risque pour Mme B d'être hétérozygote pour la maladie de Hurler est de 1/2

B. Le risque pour Mme B d'être hétérozygote pour la maladie de Hurler est de 2/3

C. Le risque pour Mme B d'être hétérozygote pour la maladie de Hurler est de 1/4

D. Le risque pour Mme B d'être hétérozygote pour la maladie de Hurler est celui de la population générale

E. Ce risque est indépendant du sexe de l'individu

QCM 2

Concernant le risque de Mr C et Mme D d'être hétérozygote pour la maladie de Hurler, quelle(s) proposition(s) est (sont) exacte(s) ?

A. Le risque pour Mr C d'être hétérozygote pour la maladie de Hurler est de 1/4

B. Le risque pour Mr C d'être hétérozygote pour la maladie de Hurler est de 2/3

C. Le risque pour Mme D d'être hétérozygote pour la maladie de Hurler est de 1/4

D. Le risque pour Mme D d'être hétérozygote pour la maladie de Hurler est de 1/3

E. Le risque pour Mme D d'être hétérozygote pour la maladie de Hurler est de 1/8

QCS 1

En vous servant de la loi de Hardy-Weinberg, quel est le risque que Mr A soit hétérozygote pour la maladie de Hurler ?

A. 1/75

B. 1/600

C. 1/300

D. 1/150

E. 1/200

QCS 2

Quel est le risque pour le couple A-B d'avoir un enfant atteint de la maladie de Hurler ?

A. 1/2 400

B. 1/1 200

C. 1/1 800

D. 1/4 800

E. 1/900

QCS 3

Quel est le risque pour le couple C-D d'avoir un enfant atteint de la maladie de Hurler ?

A. 1/128

B. 1/32

C. 1/24

D. 1/12

E. 1/48
* KILL Chap 6
* Chap 7
QCS 1

En salle de naissance, on vous confie un enfant qui présente un retard de croissance important et diverses malformations. Vous évoquez une possible triploïdie. Pour confirmer votre suspicion, vous prescrivez :

A. Un séquençage de tout le génome

B. Un caryotype constitutionnel sur lymphocytes

C. Une FISH avec une sonde du chromosome 21

D. Un Southern blot

E. Aucune de ces techniques

FISH vs caryotype
Techniques d'étude
Le caryotype

Si le caryotype a été une technique précieuse qui a permis historiquement l'identification de la majorité de ces anomalies, c'est une technique difficile, sujette à des contraintes pratiques, comprenant plusieurs étapes qui vont du recueil du prélèvement dans des conditions stériles au transport dans du milieu permettant la survie des cellules tumorales jusqu'à la mise en culture de ces cellules afin d'obtenir des cellules en division et leur analyse au stade de métaphase. Le temps de culture est variable en fonction du type tumoral et du type de culture (en suspension ou culture de cellules adhérentes). Il peut aller de 72 heures à 15 jours.

Certaines tumeurs sont difficiles à faire pousser in vitro. Les échecs de culture sont assez fréquents. Les fibroblastes du microenvironnement peuvent proliférer mieux que les cellules tumorales.

Son interprétation pose problème. Comment interpréter un caryotype sans anomalie ? Est-ce une cellule tumorale ou une cellule du microenvironnement ? Certaines anomalies comme les amplifications sont difficiles à identifier. Contrairement aux hémopathies, les tumeurs solides sont souvent polyclonales et leur caryotype peut être extrêmement complexe avec de multiples anomalies non identifiables. Beaucoup de tumeurs sont polyploïdes.

La sensibilité de cette technique n'est pas bonne (10 Mb environ) mais elle permet une analyse globale cellule par cellule des altérations.

Si le caryotype hématologique est très répandu dans les laboratoires de cytogénétiques, celui des tumeurs solides l'est peu. Il est supplanté par les techniques de cytogénétique moléculaire comme la FISH, notamment sur coupe en paraffine et la CGH-array.
La FISH

Elle peut être réalisée de première intention ou en complément du caryotype ou du profil moléculaire par CGH-array. Elle peut être réalisée sur préparation cytogénétique, apposition, empreinte, cryocoupe ou coupe en paraffine. Ces dernières ont l'avantage de garder l'architecture tumorale ce qui peut être précieux en cas de faible cellularité tumorale tout en permettant des études rétrospectives.

C'est la technique de choix pour la recherche d'amplification. Mais chaque gène à son critère d'amplification et il faut se méfier des fortes polysomies qui peuvent exister dans certaines tumeurs si on utilise des critères n'intégrant pas une sonde contrôle.
La CGH-array

C'est une étude globale du génome qui ne révèle que les variations du nombre de copies du génome, notamment les amplifications par rapport à un niveau médian. Un contrôle histologique de la cellularité tumorale de l'échantillon utilisé est nécessaire et généralement, un minimum de 50 % de cellules tumorales est requis. Des techniques se développent pour l'utiliser sur paraffine. Elle ne permet de visualiser ni les translocations ni le caractère polyclonal des tumeurs.

En 2011, un phénomène appelé chromothripsis a été décrit par Stephens et al. [9] suite à une technique de NGS. Il s'agit d'une catastrophe mitotique qui engendre une multitude de microremaniements (duplication, inversion, délétion) intéressant un (le plus souvent) mais parfois jusqu'à quatre chromosomes ou régions chromosomiques. Ils ont estimé la fréquence de ce phénomène dans les tumeurs à 2,5 % (et 5 % des tumeurs osseuses) en regardant le profil moléculaire par CGH-array. La théorie de l'accumulation progressive d'anomalies est remise en question par ce processus. Cela a été corrélé à un mauvais pronostic dans certaines tumeurs.

Le Southern blot permet l'étude d'un fragment d'ADN particulier au sein du génome après transfert des fragments d'ADN d'un gel d'électrophorèse sur une membrane
* KILL Chap 8
* KILL Chap 9
* KILL Chap 10
* KILL Chap 11
* KILL Chap 12
* Chap 13
QCS 1

Un hypertélorisme est défini par :

A. Un rapport distance intercanthale externe/distance intercanthale interne > 1/3

B. Un rapport distance intercanthale interne/distance intercanthale externe > 1/3

C. Un rapport distance intercanthale interne/distance intercanthale externe < 1/3

D. Un rapport distance intercanthale externe/distance intercanthale interne < 1/3

E. Un rapport longueur des fentes palpébrales/ distance intercanthale > 1/2

QCS 2

Un télécanthus se définit par :

A. Des fentes palpébrales étroites

B. Une chute de la paupière supérieure

C. Un déplacement latéral des canthi internes

D. Un déplacement latéral des canthi externes

E. Aucun item n'est exact

QCS 3

Un hypotélorisme se définit par :

A. Un repli à l'angle interne de l'œil

B. Une diminution de l'écartement entre les yeux

C. Un déplacement latéral des canthi internes

D. Un déplacement latéral des canthi externes

E. Aucun item n'est exact

QCS 4

Une clinodactylie se définit par :

A. Un pouce surnuméraire

B. Le blocage d'une articulation en flexion

C. La présence d'un sixième doigt au bord cubital

D. Une absence de phalange médiane

E. Aucun item n'est exact
* Chap 14
* Chap 15
QCM 1

Parmi les propositions suivantes concernant le diagnostic prénatal par échographie, laquelle/lesquelles est/sont vraie(s) ?

A. La mesure de la clarté nucale est obtenue à l'échographie de 22 SA

B. Un syndrome de Turner peut être révélé par une nuque épaisse

C. La découverte d'une nuque épaisse justifie la réalisation d'un caryotype fœtal

D. Une interposition linguale est généralement détectée à l'échographie de 12 SA

E. Les trois échographies prénatales recommandées à toute femme enceinte sont réalisées à 12, 22 et 32 SA

QCM 2

Parmi les propositions suivantes concernant les prélèvements réalisés en DPN, laquelle/lesquelles est/sont vraie(s) ?

A. L'amniocentèse est réalisée à partir de 12 SA

B. L'amniocentèse présente un risque de fausse couche de 0,1 %

C. La trophocentèse permet l'établissement d'un caryotype en 24-48 heures

D. Une détermination de sexe fœtal sur sang maternel peut être réalisée seulement à partir de 11 SA

E. Le caryotype obtenu après culture de villosités choriales est établi à partir de cellules plus proches embryologiquement du fœtus que celles utilisées pour celui de l'examen direct

QCM 3

Parmi les propositions suivantes concernant les méthodes de dépistage prénatal, laquelle/lesquelles est/sont vraie(s) ?

A. La mesure de la clarté nucale est un élément essentiel au dépistage combiné de la trisomie 21

B. Le dosage de l'α-fœtoprotéine est un élément essentiel au dépistage combiné de la trisomie 21

C. Le dépistage combiné est réalisé au premier trimestre de la grossesse

D. Le dépistage séquentiel intégré est réalisé au premier trimestre de la grossesse

E. L'ADN fœtal circulant permet le dépistage de la trisomie 21 sur sang maternel

QCM 4

Parmi les propositions suivantes concernant l'identification d'une mosaïque 46,XX/47,XX,+21 obtenue à l'examen direct après trophocentèse, laquelle/lesquelles est/sont vraie(s) ?

A. Une contamination par des cellules maternelles doit être suspectée

B. Une trisomie 21 en mosaïque vraie doit être suspectée

C. Une mosaïque confinée au placenta doit être suspectée

D. Une IMG peut être proposée au regard de ces résultats

E. Le caryotype permet de distinguer une contamination maternelle d'une trisomie 21 en mosaïque vraie

QCM 5

Parmi les propositions suivantes, quelles sont celles justifiant un diagnostic préimplantatoire en France ?

A. Un couple ayant eu un enfant atteint d'une myotonie de Steinert

B. Un couple ayant eu un enfant atteint de daltonisme

C. Une mère conductrice de myopathie de Duchenne n'ayant pas eu d'enfant atteint

D. Un antécédent de trisomie 21 libre et homogène

E. Un couple dont les deux membres ont une mutation p.Phe508del à l'état hétérozygote
* Chap 16
QCM

QCM 1

Concernant les prélèvements nécessaires pour les dépistages biochimiques :

A. Il peut être fait durant le 2e jour de vie

B. Il peut être fait dans le 3e jour de vie

C. Les prélèvements sont collectés sur un buvard

D. Les prélèvements sont envoyés à un centre régional

E. Une information spécifique est donnée au préalable du prélèvement

QCM 2

Concernant les prélèvements nécessaires pour les dépistages biochimiques :

A. Un consentement signé est nécessaire pour l'évaluation du risque de drépanocytose

B. Un consentement signé est nécessaire pour l'évaluation du risque de la mucoviscidose

C. Un consentement signé est nécessaire pour l'évaluation du risque de l'hyperplasie surrénale congénitale

D. Un enfant dont les deux parents sont nés aux Antilles doit bénéficier du dépistage ciblé de la drépanocytose

E. Un enfant dont la mère est née au Maghreb et dont le père n'est pas connu doit bénéficier du dépistage ciblé de la drépanocytose

QCM 3

Concernant les maladies dépistées par le dépistage biochimique :

A. Le taux de faux positif pour l'hyperplasie surrénale congénitale est important chez les enfants prématurés

B. Le dépistage de l'hypothyroïdie en France ne permet pas le dépistage des hypothyroïdies d'origine hypophysaire

C. Un dosage des hormones thyroïdiennes est nécessaire chez les enfants présentant une malformation médiane de la face

D. Les hyperphénylalaninémies sont toutes liées à un déficit de la phénylalanine hydroxylase

E. Une malformation génitale est souvent associée aux formes sévères d'hyperplasie surrénale congénitale chez les nouveaux nés 46,XX

QCM 4

Concernant le conseil génétique après dépistage :

A. Le dépistage de la drépanocytose permet de mettre en évidence la plupart des sujets hétérozygotes au locus β-globine

B. Le dépistage de la mucoviscidose permet de mettre en évidence la plupart des sujets hétérozygotes au locus CFTR

C. Un sujet porteur d'une forme classique d'hyperplasie surrénale est homozygote ou hétérozygote composite pour des allèles sévères

D. Le frère normal d'un sujet porteur d'une mucoviscidose à 2/3 de risque d'être hétérozygote si ses parents sont de phénotype habituel

E. Un sujet porteur d'une surdité dépistée en période néonatale a le plus souvent un parent sourd

QCM 5

Concernant le dépistage de la surdité :

A. Il est fondé sur l'utilisation des otoémissions acoustiques ou des PEA

B. La valeur prédictive négative du test est bonne

C. Tous les types de surdité sont détectables en période néonatale

D. L'objectif principal est de permettre la prise en charge précoce d'une surdité sévère permettant la mise en place d'une communication verbale si possible

E. Le nombre des faux positifs est important
* Chap 17
* Chap 18


QROC 1

Citez les principes à respecter lors de la prescription et la réalisation de tests génétiques (examens des caractéristiques génétiques de la personne).

QROC 2

Caractéristiques de l'information préalable au recueil du consentement.

QROC 3

Caractéristiques de l'information lors du rendu de résultat.

QROC 4

Dans quelles circonstances faut-il mettre en œuvre la démarche d'information familiale en génétique ?

QROC 5

Lorsqu'une affection génétique est diagnostiquée, qui doit informer la parentèle ?

QROC 6

Conditions de prescription des tests génétiques pour les mineurs et les majeurs sous tutelle.
* Chap 19
QROC 2

À quelles conditions la loi autorise-t-elle le recours à l'interruption de grossesse pour motif médical ?
* Chap 20
* Chap 21
* Chap 22
QCM 2

Dans la famille représentée ci-dessous, les garçons II.1 et II.2 sont atteints du syndrome de l'X fragile (FXS). On a indiqué le nombre de triplets CGG dans le gène FMR1 pour la mère et les enfants. Indiquez la/les proposition(s) vraie(s) :
u22-02-9782294745218

A. Le garçon II.2 présente une déficience intellectuelle plus importante que son frère II.1

B. La femme I.2 peut avoir des enfants porteurs d'un allèle normal, d'une prémutation ou d'une mutation complète

C. Il n'y a pas d'autre cas de déficience intellectuelle dans la famille. I.2 rapporte simplement une ataxie chez son père depuis l'âge de 65 ans mais cela ne peut pas avoir de lien avec le gène FMR1

D. Le génotype de II.4 a été déterminé dans le cadre d'un diagnostic prénatal et a mis en évidence chez le fœtus de sexe féminin respectivement 30 et 300 répétitions CGG. Vous annoncez aux parents qu'il s'agit d'une mutation complète et que le pronostic est le même que pour un garçon

QCM 3

Dans la famille représentée ci-dessous, l'enfant III.2, fille âgée de 4 ans présente un retard des acquisitions et des troubles du comportement de type autistique qui a fait évoquer un syndrome de l'X fragile (FXS) qui a été confirmé par la mise en évidence d'une mutation complète dans le gène FMR1. Quelle(s) sont la/les proposition(s) juste(s) ?
u22-03-9782294745218

A. La mère ou le père de la patiente III.2 est porteur d'une prémutation et leurs sœurs respectives (II.2 et II.5), qui sont enceintes de garçons, sont à risque d'être porteuses de la mutation familiale et d'avoir un fils atteint de FXS. Vous préconisez de faire réaliser d'urgence une analyse génétique chez eux dans le cadre du conseil génétique pour II.2 et II.5

B. Vous calculez que si II.3 est prémutée, sa sœur a 75 % de risque de l'être également

C. Après analyse génétique, il s'avère que la mère de la patiente III.2 est porteuse d'une prémutation. Cette jeune femme, II.3, a 31 ans et le souhait d'un troisième enfant. Vous l'informez qu'étant porteuse d'une prémutation, sa fertilité peut être impactée

D. Les enfants des patients porteurs d'une mutation du FXS sont tous porteurs d'une mutation complète car la mutation ne rétracte pratiquement jamais vers une prémutation ou un allèle normal

QCM 4
QCM 7

Dans le cas de la myotonie de Steinert, indiquez quelle(s) sont la/les proposition(s) juste(s) ?

A. C'est une maladie responsable d'une forme congénitale de maladie musculaire qui est extrêmement rare chez l'adulte

B. Une cataracte peut être la seule expression clinique de la myotonie de Steinert

C. Au sein d'une famille, si différentes formes cliniques sont observées, elles ont tendance à s'aggraver au cours des générations

D. Il n'y a pas d'atteinte cognitive dans la myotonie de Steinert
* Chap 23
QCM 5

Quelle(s) est/sont la/les caractéristique(s) des cancers du sein associés aux mutations du gène BRCA1 ?

A. La rapidité évolutive

B. Le profil triple négatif vis-à-vis des récepteurs aux œstrogènes à la progestérone et de l'amplification d'ERBB2

C. Une sensibilité particulière aux inhibiteurs de PARP

D. Leur présentation multifocale

E. Leur bon pronostic
* KILL Chap 24
* KILL Chap 25
* KILL Chap 26
* Chap 27
QCM 1

Dans le cadre du dépistage de la trisomie 21, le calcul du dépistage combiné proposé au premier trimestre est basé sur :

A. La mesure de la clarté nucale

B. L'âge maternel

C. L'âge paternel

D. les antécédents d'anomalie chromosomique dans la fratrie

E. La présence d'une cardiopathie congénitale

QCM 2

Quel suivi régulier doit être proposé aux enfants porteurs d'une trisomie 21 ?

A. ORL

B. Ophtalmologique

C. Cardiaque

D. Urologique

E. Orthopédique

QCM 3

Quelle(s) complication(s) est/sont à redouter chez l'adulte trisomique 21 ?

A. Sécheresse cutanée

B. Cataracte

C. Dysurie

D. Syndrome parkinsonien

E. Syndrome démentiel de type Alzheimer

QCM 4

Quelles complications sont à redouter durant la première année de vie chez un(e) enfant porteur/euse de trisomie 21 ?

A. Cataracte

B. Leucémie aiguë

C. Syndrome de West

D. Apnées du sommeil

E. Maladie cœliaque

QCM 5

Les enfants porteurs de trisomies 21 sont plus fréquemment soumis à :

A. Apnées du sommeil

B. Infections

C. Tumeurs solides

D. Instabilité C1-C2

E. Diabète

QCM 6

La prise en charge des enfants porteurs de trisomie 21 :

A. N'est pas forcément multidisciplinaire

B. Nécessite l'investissement des parents

C. Nécessite de l'orthophonie

D. Ne nécessite pas d'aide psychologique

E. Nécessite un apport vitaminique augmenté

QCM 7

L'adulte porteur de trisomie 21 :

A. Ne peut pas travailler

B. Doit rester chez ses parents

C. Doit généralement être mis sous une mesure de protection

D. Peut intégrer une structure de type ESAT

E. Ne peut pas pratiquer de sport

QCM 8

Quelle(s) est(sont) la(les) malformation(s) digestive(s) la(les) plus fréquente(s) chez un nouveau-né trisomique 21 ?

A. Imperforation anale

B. Atrésie duodénale

C. Atrésie de l'œsophage

D. Présence d'une rate surnuméraire

E. Mésentère commun

QCM 9

Quelles formules chromosomiques sont compatibles avec un tableau clinique de trisomie 21 ?

A. 47,XXY

B. 45,XX,der(14 ;21)(q10 ;q10)

C. 45,X

D. 47,XY,+21

E. 46,XY,der(14;21)(q10;q10),+21

QCS 1

Le diagnostic de trisomie 21 en période anténatale s'effectue avec :

A. Le dosage des marqueurs sériques maternels

B. L'échographie

C. L'âge de la mère

D. L'âge du père

E. Le caryotype fœtal

QCS 2

Quelle est la malformation à rechercher en priorité à la naissance chez un enfant porteur de trisomie 21 ?

A. Cardiaque

B. Digestive

C. Rénale

D. Cérébrale

E. Vertébrale

QCS 3

Quel organisme est chargé de l'orientation des enfants trisomiques 21 ?

A. SESSAD

B. CAMSP

C. MDPH

D. CLIS

E. CDES

QCS 4

Quelle complication biologique doit être recherchée régulièrement chez les enfants porteurs de trisomie 21 ?

A. Hyperuricémie

B. Anémie

C. Hypothyroïdie

D. Hypernatrémie

E. Protéinurie

QCS 5

Quelle complication néoplasique est à redouter particulièrement chez les enfants porteurs de trisomie 21 ?

A. Lymphome

B. Sarcome

C. Tumeur cérébrale

D. Leucémie aiguë myéloïde

E. Hépatocarcinome

QCS 6

Quel est le type cytogénétique le plus fréquent de trisomie 21 ?

A. Trisomie 21 en mosaïque

B. Trisomie 21 par translocation robertsonienne

C. Trisomie 21 par translocation réciproque

D. Trisomie 21 libre et homogène

E. Trisomie 21 partielle

QCS 7

Quel est le risque de récurrence de trisomie 21 pour un couple ayant eu un enfant porteur de trisomie 21 secondaire à une mauvaise disjonction d'une translocation 14 ; 21 d'origine maternelle ?

A. 1 %

B. 100 %

C. 50 %

D. 15 %

E. 3 %

QCS 8

Quel est le risque de récurrence de trisomie 21 pour un couple ayant eu un enfant porteur d'une trisomie 21 libre et homogène ? L'âge de la femme est de 30ans :

A. 1 %

B. 100 %

C. 50 %

D. 15 %

E. 2 %

QCS 9

Trisomie 21 et procréation :

A. Les adultes porteurs de trisomies 21 sont stériles

B. Les enfants nés d'hommes trisomiques 21 sont tous porteurs de T21

C. Seulement les hommes porteurs de T21 sont stériles

D. Les personnes trisomiques 21 (T21 libre) ont un risque théorique de 50 % de conception trisomique 21

E. Les femmes trisomiques 21 n'ont pas de risque de donner naissance à un enfant trisomique 21

QCS 10

Les enfants porteurs de trisomie 21 :

A. N'acquièrent jamais la marche

B. Acquièrent le langage à la même période que les enfants non trisomiques

C. Ont une sensibilité à la douleur augmentée

D. Ne doivent pas être vaccinés

E. Peuvent réagir différemment à certains médicaments

QCS 11

La trisomie 21 :

A. Touche uniquement les populations européennes

B. Est la première cause de déficience intellectuelle d'origine génétique

C. Est médicalement nommé « mongolisme »

D. Est une pathologie acquise

E. Ne peut pas être diagnostiqué en période néonatale
* Chap 28
QCM 1

La mucoviscidose est diagnostiquée classiquement en France :

A. Sur signes cliniques de bronchopathie chronique dans les premières années de vie

B. Au cours du suivi échographique de la grossesse par la découverte d'un intestin hyperéchogène

C. Par un dépistage systématique des nouveau-nés au troisième jour de vie

QCS 1

La mucoviscidose est une maladie monogénique :

A. Qui se transmet selon un mode de transmission dominant

B. Qui se transmet selon un mode de transmission récessif lié à l'X

C. Qui se transmet selon un mode de transmission autosomique récessif avec une pénétrance incomplète

D. Qui se transmet selon un mode de transmission récessif avec pénétrance complète

QCS 2

Le gène de la mucoviscidose (le gène CFTR) a été cloné :

A. Grâce à une stratégie gène candidat

B. Par une étude réussie de GWAS (pour genome-wide association study)

C. Par une étude directe en s'appuyant sur la connaissance de la séquence de la protéine

D. Par une stratégie de clonage positionnel

QCS 3

La fréquence des porteurs à l'état hétérozygote d'une mutation dans le gène CFTR dans la population française est de :

A. 1/100

B. 1/50

C. 1/30

D. 1/500

QCS 4

Quel est le risque pour un couple pris au hasard dans la population de donner naissance à un enfant atteint de mucoviscidose ?

A. 1/10 000

B. 1/4 000

C. 1/50 000

QCS 5

Quel est le risque a priori de donner naissance à un enfant atteint pour un couple dont l'un des conjoints est porteur d'une mutation dans le gène CFTR :

A. 1/60

B. 1/120

C. 1/240

D. 1/500

QCS 6

Quel est le risque a priori d'être porteur d'une mutation dans le gène CFTR pour le frère non malade d'un sujet atteint :

A. 1/2

B. 2/3

C. 1/4

D. 1/8

QCS 7

La mutation F508del (p.Phe508del) est la mutation la plus fréquente du gène CFTR. Il s'agit :

A. D'une mutation d'épissage

B. D'une mutation troncative

C. D'une délétion rompant le cadre de lecture

D. D'une délétion respectant le cadre de lecture

QCS 8

La majorité des 2 000 mutations identifiées dans le gène CFTR responsable de la mucoviscidose sont des mutations :

A. Faux-sens

B. Non-sens

C. Des insertions/délétions

D. Des expansions de triplets

E. Des grands réarrangements génomiques
* Chap 29
QCM 1

Concernant le syndrome de l'X fragile, quelles sont les propositions vraies ?

A. Il s'agit de la forme de déficience intellectuelle d'origine génétique la plus fréquente

B. La macro-orchidie est un élément essentiel du diagnostic chez les jeunes garçons

C. Les patients présentent souvent des troubles du spectre autistique

D. Certains patients ont un QI dans les normes

E. Les conductrices peuvent présenter une déficience intellectuelle

QCM 2

Concernant les prémutations du gène FMR1, quelles sont les propositions vraies ?

A. Elles correspondent aux allèles comportant 55 à 250 répétitions CGG

B. Le risque qu'elles soient transmises par un homme porteur à toutes ses filles est proche de 100 %

C. Elles sont associées à un risque d'insuffisance ovarienne prématurée

D. Le risque de syndrome neurodégénératif à début tardif (FXTAS) ne concerne que les hommes

E. Elles peuvent passer à la mutation complète lors d'une transmission paternelle

QCS 1

Concernant le syndrome de l'X fragile, quelles sont les propositions vraies ?

A. Il est peut-être causé par une mutation ponctuelle du gène FMR1

B. Les mutations surviennent le plus souvent de novo

C. La CGH-array confirme le diagnostic chez la plupart des patients

D. Les caractéristiques faciales ne sont ni constantes ni spécifiques

E. Le diagnostic prénatal peut être proposé à une femme dont le conjoint est porteur d'une prémutation
* Bonus : PEC BRCA
Prise en charge des femmes porteuses d'une mutation d'un gène BRCA

■ À partir de 20 ans, palpation des seins et des creux axillaires tous les 6 mois.

■ À partir de 30 ans, ou 5 ans avant le cas de cancer du sein s'il existe un cas avant 30 ans, IRM mammaire annuelle, complétée d'une seule incidence de mammographie.

■ Avant 40 ans, en particulier chez les porteuses d'une mutation de BRCA1, après information, temps de réflexion et accompagnement psychologique mastectomie prophylactique.

■ Après 40 ans et tout projet parental, annexectomie prophylactique.
* Bonus: Lynch
* Bonus: PEC MMR
Prise en charge des porteurs et porteuses d'une mutation d'un gène MMR

■ À partir de 20 ans, chromocoloscopie complète tous les deux ans.

■ À partir de 30 ans, échographie endovaginale avec prélèvement endométrial par Pipelle de Cornier tous les deux ans.

■ Après 40 ans et accomplissement du projet parental, hystérectomie avec ovariectomie prophylactique.
* Bonus: noms des gènes
| Forme héréditaire de cancer                                | Gène         | Name                                       |
|------------------------------------------------------------+--------------+--------------------------------------------|
| I. Activation constitutive de la cascade de transduction   |              |                                            |
|------------------------------------------------------------+--------------+--------------------------------------------|
| Cancer médullaire de la thyroïde (CMT)                     | RET          | REarranged during Transfection             |
| Cancer papillaire du rein                                  | MET          | Mesenchymal Epithelial Transition          |
| Maladie de Cowden                                          | PTEN         | Phosphatase and TENsin homolog,            |
| Maladie de Von Hippel Lindau                               | VHL          | idem                                       |
| Médulloblastome                                            | SUFU         | Suppressor Of Fused Homolog (hedgehog !)   |
| Neurofibromatose de type I                                 | NF1          | idem                                       |
| Polypose adénomateuse familiale                            | APC          | Adenomatous Polyposis coli                 |
| Syndrome de Gorlin                                         | PTCH         | PaTCH                                      |
| Tumeur de Wilms                                            | WT1          | Wil's Tumor                                |
|------------------------------------------------------------+--------------+--------------------------------------------|
| II. Altération des points de contrôles du cycle cellulaire |              |                                            |
|------------------------------------------------------------+--------------+--------------------------------------------|
| Rétinoblastome                                             | RB1          | idem                                       |
| Mélanome malin                                             | CDKN2A       | Cyclin Dependent Kinase Inhibitor          |
| Syndrome de Li-Fraumeni                                    | TP53         | Tumor Protein                              |
|------------------------------------------------------------+--------------+--------------------------------------------|
| III. Altération des systèmes de réparation de l'ADN        |              |                                            |
|------------------------------------------------------------+--------------+--------------------------------------------|
| Cancer du sein et de l'ovaire                              | BRCA1, BRCA2 | BReast CAncer                              |
| Polypose adénomateuse autosomique récessive                | MUTYH        | Mut Y DNA glycosylase                      |
|                                                            | MLH1         | MuLt Homolog                               |
| Syndrome de Lynch                                          | MSH          | DNA repair MiSmatcH                        |
| Xeroderma pigmentosum                                      | XP           | idem                                       |
|------------------------------------------------------------+--------------+--------------------------------------------|
| Autres                                                     |              |                                            |
|------------------------------------------------------------+--------------+--------------------------------------------|
| Cancers bronchiques                                        | ALK          | Activin receptor-Like Kinase 1             |
| Carcinomes colique, bronchiques                            | KRAS         | Kirsten RAt Sarcoma viral oncogene homolog |
| Carcinomes sein, ovaire                                    | HER2         | Human Epidermal growth factor Receptor 2   |
| Carcinomes+++, gliomes                                     | EGFR         | Epidermal Growth Factor Receptor           |
| GastroIntestinal STromal Tumor                             | KIT          |                                            |
| Leucémies aigües myéloïdes                                 | FLT3         | Fms-Like Tyrosine kinase 3                 |
| Leucémies, mélanomes                                       | NRAS         | Neuroblastoma-RAS                          |
| Lymphome de Burkitt                                        | C-MYC        | Cellular MYeloCytomatosis                  |
| Lymphomes du manteau                                       | Cycline D    |                                            |
| Mélanome                                                   | CD4          | Cluster of differentiation 4               |
| Mélanomes                                                  | BRAF         |                                            |
| Neuroblastomes                                             | N-MYC        |                                            |
| Sarcomes, gliomes                                          | PDGFR        | Platelet-derived growth factor receptors   |
